name: navigation_vocale_example
description: Application Navigation Vocale mains-libres pour Thinkphone
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  navigation_vocale:
    path: ../
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
